export const GET_TEAMS = 'GET_TEAMS';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_ERROR = 'GET_TEAMS_ERROR';
export const GET_SELECTED_TEAM = 'GET_SELECTED_TEAM';
export const GET_SELECTED_TEAM_SUCCESS = 'GET_SELECTED_TEAM_SUCCESS';
export const GET_SELECTED_TEAM_ERROR = 'GET_SELECTED_TEAM_ERROR';